// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");

Jest.test("addition", (function () {
        return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](7));
      }));

/*  Not a pure module */
