// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var ReasonReact = require("reason-react/src/ReasonReact.js");
var Home$Workhours = require("./home.bs.js");
var Login$Workhours = require("./Login.bs.js");
var NewWork$Workhours = require("./newWork.bs.js");
var WorkList$Workhours = require("./workList.bs.js");

function urlToRoute(url) {
  var match = url[/* path */0];
  if (match) {
    switch (match[0]) {
      case "edit" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Edit */1;
          }
      case "list" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* List */2;
          }
      case "login" : 
          if (match[1]) {
            return /* Home */0;
          } else {
            return /* Login */3;
          }
      default:
        return /* Home */0;
    }
  } else {
    return /* Home */0;
  }
}

function routeToString(route) {
  switch (route) {
    case 0 : 
        return "/";
    case 1 : 
        return "/edit";
    case 2 : 
        return "/list";
    case 3 : 
        return "/login";
    
  }
}

function routeToComponent(route, workList, handleAction) {
  switch (route) {
    case 0 : 
        return ReasonReact.element(undefined, undefined, Home$Workhours.make(workList, handleAction, /* array */[]));
    case 1 : 
        return ReasonReact.element(undefined, undefined, NewWork$Workhours.make(/* array */[]));
    case 2 : 
        return ReasonReact.element(undefined, undefined, WorkList$Workhours.make(workList, /* array */[]));
    case 3 : 
        return ReasonReact.element(undefined, undefined, Login$Workhours.make(/* array */[]));
    
  }
}

exports.urlToRoute = urlToRoute;
exports.routeToString = routeToString;
exports.routeToComponent = routeToComponent;
/* ReasonReact Not a pure module */
