// Generated by BUCKLESCRIPT VERSION 4.0.5, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var List = require("bs-platform/lib/js/list.js");
var WorkList$Workhours = require("./workList.bs.js");

function createWorkOnDate(id, date) {
  return /* record */[
          /* id */id,
          /* start */date,
          /* duration */1,
          /* lunch */0,
          /* userid */"testerman"
        ];
}

function dateHelp(param) {
  return (function (param$1) {
      var param$2 = param;
      var param$3 = 8;
      var param$4 = 0;
      return new Date(2018, 6, param$2, param$3, param$4);
    });
}

Jest.test("workListToCurrentWeek", (function () {
        var testDate = new Date(2018, 6, 19, 14, 0);
        var list_000 = createWorkOnDate("1", dateHelp(14)(/* () */0));
        var list_001 = /* :: */[
          createWorkOnDate("2", dateHelp(15)(/* () */0)),
          /* :: */[
            createWorkOnDate("3", dateHelp(16)(/* () */0)),
            /* :: */[
              createWorkOnDate("4", dateHelp(17)(/* () */0)),
              /* :: */[
                createWorkOnDate("5", dateHelp(18)(/* () */0)),
                /* :: */[
                  createWorkOnDate("6", dateHelp(19)(/* () */0)),
                  /* :: */[
                    createWorkOnDate("7", dateHelp(20)(/* () */0)),
                    /* :: */[
                      createWorkOnDate("8", dateHelp(21)(/* () */0)),
                      /* :: */[
                        createWorkOnDate("9", dateHelp(22)(/* () */0)),
                        /* [] */0
                      ]
                    ]
                  ]
                ]
              ]
            ]
          ]
        ];
        var list = /* :: */[
          list_000,
          list_001
        ];
        return Jest.Expect[/* toBe */2](7, Jest.Expect[/* expect */0](List.length(WorkList$Workhours.workListToCurrentWeek(testDate, list))));
      }));

exports.createWorkOnDate = createWorkOnDate;
exports.dateHelp = dateHelp;
/*  Not a pure module */
